"""Create initial tables

Revision ID: c41c77f9fdec
Revises:
Create Date: 2025-11-29 18:11:13.567136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c41c77f9fdec"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("PARENT", "SITTER", "ADMIN", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "INACTIVE",
                "SUSPENDED",
                name="userstatus",
            ),
            nullable=False,
        ),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column(
            "profile_image_url",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "is_email_verified", sa.Boolean(), nullable=False
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_email"), "users", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_users_role"), "users", ["role"], unique=False
    )
    op.create_index(
        op.f("ix_users_status"), "users", ["status"], unique=False
    )
    op.create_table(
        "parent_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column(
            "number_of_children", sa.Integer(), nullable=True
        ),
        sa.Column(
            "children_age_range",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "max_hourly_rate",
            sa.Numeric(precision=8, scale=2),
            nullable=True,
        ),
        sa.Column(
            "address_street", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "address_city", sa.String(length=100), nullable=True
        ),
        sa.Column(
            "address_state", sa.String(length=50), nullable=True
        ),
        sa.Column(
            "address_zip", sa.String(length=20), nullable=True
        ),
        sa.Column(
            "special_requirements", sa.Text(), nullable=True
        ),
        sa.Column("has_pets", sa.Boolean(), nullable=False),
        sa.Column("pets_description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_parent_profiles_user_id"),
        "parent_profiles",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "sitter_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("birth_date", sa.DateTime(), nullable=True),
        sa.Column(
            "hourly_rate",
            sa.Numeric(precision=8, scale=2),
            nullable=True,
        ),
        sa.Column(
            "years_of_experience", sa.Integer(), nullable=True
        ),
        sa.Column(
            "has_transportation", sa.Boolean(), nullable=False
        ),
        sa.Column(
            "max_travel_distance", sa.Integer(), nullable=True
        ),
        sa.Column(
            "address_city", sa.String(length=100), nullable=True
        ),
        sa.Column(
            "address_state", sa.String(length=50), nullable=True
        ),
        sa.Column(
            "background_check_completed",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "background_check_date",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_sitter_profiles_user_id"),
        "sitter_profiles",
        ["user_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sitter_profiles_user_id"),
        table_name="sitter_profiles",
    )
    op.drop_table("sitter_profiles")
    op.drop_index(
        op.f("ix_parent_profiles_user_id"),
        table_name="parent_profiles",
    )
    op.drop_table("parent_profiles")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
